name: ftp

on: push

jobs:

  buildNdeploy:
    name: build et ftp
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: nicolasproject.hd.free.fr
          username: nicolascir
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          server-dir: ./siteweb/public/